# Generated by Django 4.1.7 on 2023-02-27 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="messages", old_name="chat_id", new_name="chat",
        ),
    ]
