# Generated by Django 4.1.7 on 2023-02-27 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_rename_chat_id_messages_chat"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
