# Generated by Django 4.1.7 on 2023-02-28 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_chat_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="image",
            field=models.FileField(null=True, upload_to="chatroom_images"),
        ),
        migrations.AlterField(
            model_name="messages",
            name="image",
            field=models.FileField(null=True, upload_to="message_images"),
        ),
    ]
