# Generated by Django 4.0 on 2023-03-01 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_messageimage_alter_messages_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='image',
        ),
        migrations.DeleteModel(
            name='MessageImage',
        ),
    ]
