# Generated by Django 4.0 on 2023-03-02 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_appuser_learning_alter_appuser_native'),
        ('chat', '0006_remove_messages_image_delete_messageimage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Messages',
            new_name='Message',
        ),
    ]
