# Generated by Django 4.1.7 on 2023-02-26 14:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("connect", "0002_rename_connection_request_connectionrequest"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="connectionrequest", unique_together={("request_from", "request_to")},
        ),
    ]
