# Generated by Django 4.1.7 on 2023-02-24 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="appuser", name="handle",),
        migrations.AddField(
            model_name="appuser",
            name="learning",
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name="appuser",
            name="native",
            field=models.CharField(max_length=3, null=True),
        ),
    ]
