# Generated by Django 4.1.7 on 2023-02-24 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_remove_appuser_handle_appuser_learning_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appuser", name="description", field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="appuser",
            name="profile_img",
            field=models.FileField(null=True, upload_to="profile_images"),
        ),
    ]
