# Generated by Django 4.1.7 on 2023-02-26 11:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_appuser_status_alter_appuser_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="appuser",
            name="connections",
            field=models.ManyToManyField(
                blank=True, null=True, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
