# Generated by Django 4.1.7 on 2023-02-26 11:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0005_appuser_connections"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appuser",
            name="connections",
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
