# Generated by Django 4.0 on 2023-03-02 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_appuser_groups_alter_appuser_user_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='learning',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='native',
            field=models.CharField(max_length=3),
        ),
    ]
