# Generated by Django 4.1.7 on 2023-02-25 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.FileField(null=True, upload_to="post_images"),
        ),
    ]
