# Generated by Django 4.1.7 on 2023-02-25 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0002_alter_post_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="date_created",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
