# Generated by Django 4.1.7 on 2023-02-26 08:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("post", "0005_likes_comments"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="likes", unique_together={("post_id", "liked_by")},
        ),
    ]
