# Generated by Django 4.0 on 2023-03-02 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_appuser_learning_alter_appuser_native'),
        ('post', '0007_alter_comments_post_id_alter_likes_post_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
        migrations.RenameModel(
            old_name='Likes',
            new_name='Like',
        ),
    ]
