name: CI Test

on: [push] 

jobs:
  test_backend:
    runs-on: ubuntu-latest # operating system your code will run on
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python  
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      working-directory: ./project-backend
    - name: Run Tests
      env: 
        CONNECT_BACKEND_SECRET_KEY: ${{ secrets.CONNECT_BACKEND_SECRET_KEY }} 
      run: |
        python manage.py test
      working-directory: ./project-backend/socialnetworkbackend
      
